
# https://learn.microsoft.com/en-us/azure/aks/concepts-storage#volumes
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_ZRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# The PV could be created statically or dynamically
# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-managed-disk
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: myAzureDisk
    diskURI: /subscriptions/{subscription-id}/resourceGroups/{group-name}/providers/Microsoft.Compute/disks/{disk-name}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-premium-retain

---

# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  volumeName: azure-managed-disk
  resources:
    requests:
      storage: 5Gi

---
# Pod
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - name: myfrontend
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-app
  template:
    metadata:
      labels:
        app: sql-app
    spec:
      containers:
      - name: sql-container
        image: your-sql-image
        volumeMounts:
        - name: sql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: sql-storage
        persistentVolumeClaim:
          claimName: azure-disk-pvc
---
file share on azure
https://medium.com/dataseries/creating-persistent-volume-in-azure-kubernetes-service-aks-using-azure-files-2a48d4e08fb8